### ISSUE TITLE
The game is capped at 60FPS in fullscreen on proton; -f has no effect

### ISSUE THREAD

**Issue by vincent-hugot** [gurrgur/er-patcher#77] opened 2024-06-30 08:12 UTC
> python er-patcher -v -sr 144 -- protonhax init env  MANGOHUD=1 gamemoderun %command% > ~/___log

Works in borderless. 

However, the game is capped at 60FPS in fullscreen. 

The documentation of -f suggests this should not happen under proton.
-f Makes no difference.

I'm on Proton Experimental.

Possibly related to #74 .

**Comment by gurrgur** [comment] 2024-06-30 13:00
You have to use borderless fullscreen to workaround the 60fps lock for the time being. Closing as duplicate of #74

**Closed by gurrgur** 2024-06-30 13:00 UTC
